service: game-descriptor
runtime: python310
instance_class: F4  # 1536 MB of memory
service_account: game-descriptor-worker@webhost-common.iam.gserviceaccount.com
entrypoint: gunicorn -b :$PORT app.views:app --timeout 180

automatic_scaling:
  max_instances: 3

env_variables:
  MODEL_BUCKET: prod_steam_game_descriptor_data
  TEMP_BUCKET: prod_temp_lf345f
  TEMP_BUCKET_PREFIX: steam_game_descriptor/v2/descriptions
  IMG_BUCKET: prod_steam_game_descriptor_img